version: '3.9'

services:
  api:
    build:
      context: api
    environment:
      - UVICORN_RELOAD=true
      - API_KEY=12345678
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app

  web:
    build:
      context: web
    entrypoint: /code/entrypoint.sh
    volumes:
      - ./web:/code
    environment:
      - DJANGO_SETTINGS_MODULE=okgbi.settings
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME:-admin}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-admin@example.com}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD:-admin}
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./web/staticfiles:/static
    depends_on:
      - web

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}


volumes:
  postgres_data:
