version: '3.9'

services:
  api:
    build:
      context: api
    entrypoint: /code/entrypoint.sh
    volumes:
      - ./api/staticfiles:/code/staticfiles
      - ./api/media:/code/media
    environment:
      - DJANGO_SETTINGS_MODULE=okgbi.settings
      - DEBUG=False
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    volumes:
      - ./api/staticfiles:/static
      - ./api/media:/media
    ports:
      - "80:80"
    depends_on:
      - api

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  postgres_data: