# Generated by Django 5.2 on 2025-07-25 06:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактная информация')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyRetooling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(help_text='Number of retooling operations on this date')),
                ('price', models.DecimalField(decimal_places=2, help_text='Total cost of retooling operations', max_digits=16)),
            ],
            options={
                'verbose_name': 'Daily Retooling',
                'verbose_name_plural': 'Daily Retoolings',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('length', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Длина, мм')),
                ('width', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ширина, мм')),
                ('height', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Высота, мм')),
                ('concrete_class', models.CharField(max_length=10, verbose_name='Класс бетона')),
                ('wire_bottom', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Проволока верх, шт')),
                ('wire_top', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Проволока низ, шт')),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
            },
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('length', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('concrete_class', models.CharField(max_length=10)),
                ('wire_bottom', models.PositiveIntegerField()),
                ('wire_top', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField()),
                ('order', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('plate_type', models.CharField(choices=[('production', 'Production Day Plate'), ('used', 'Used Ready Plate'), ('unplaced', 'Unplaced Plate'), ('left', 'Left Ready Plate')], default='production', max_length=20)),
            ],
            options={
                'verbose_name': 'Plate',
                'verbose_name_plural': 'Plates',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, verbose_name='Номер заказа')),
                ('count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество, шт')),
                ('deadline', models.DateField(null=True, verbose_name='Дедлайн по заказу')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_length', models.PositiveIntegerField(verbose_name='Длина дорожки')),
                ('default_available_tracks', models.PositiveIntegerField(default=4, verbose_name='Количество дорожек по умолчанию')),
                ('tracks_count', models.PositiveIntegerField(default=7, verbose_name='Количество дорожек')),
                ('production_lag', models.PositiveIntegerField(default=3, verbose_name='Производственный лаг (в днях)')),
                ('tail_length', models.PositiveIntegerField(default=2000, help_text='Критическая длина хвоста в мм., при превышении которой хвост будет перенесен в конец', verbose_name='Длина хвоста')),
                ('force_tail', models.IntegerField(choices=[(0, 'Мягкий режим'), (1, 'Средний режим'), (2, 'Жесткий режим')], default=0, help_text='0 - мягкий режим, 1 - средний режим, 2 - жесткий режим', verbose_name='Режим переноса хвоста')),
                ('url_1c', models.CharField(default='', max_length=255, verbose_name='URL 1c')),
                ('sign_1c', models.CharField(default='123456788', max_length=255, verbose_name='Пароль 1с')),
                ('monday_weekend', models.BooleanField(default=False, verbose_name='Понедельник')),
                ('tuesday_weekend', models.BooleanField(default=False, verbose_name='Вторник')),
                ('wednesday_weekend', models.BooleanField(default=False, verbose_name='Среда')),
                ('thursday_weekend', models.BooleanField(default=False, verbose_name='Четверг')),
                ('friday_weekend', models.BooleanField(default=False, verbose_name='Пятница')),
                ('saturday_weekend', models.BooleanField(default=True, verbose_name='Суббота')),
                ('sunday_weekend', models.BooleanField(default=True, verbose_name='Воскресенье')),
            ],
            options={
                'verbose_name': 'Параметры',
                'verbose_name_plural': 'Параметры',
            },
        ),
        migrations.CreateModel(
            name='ProductionDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('height', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('useful_len', models.PositiveIntegerField()),
                ('free_len', models.PositiveIntegerField()),
                ('concrete_class', models.CharField(max_length=10)),
                ('wire_bottom', models.PositiveIntegerField()),
                ('wire_top', models.PositiveIntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=16)),
                ('free_cost', models.DecimalField(decimal_places=2, max_digits=16)),
                ('full_cost', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
            options={
                'verbose_name': 'Production Day',
                'verbose_name_plural': 'Production Days',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='RetoolingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Total cost of all retooling operations', max_digits=16)),
                ('last_state_width', models.PositiveIntegerField(help_text='Last width setting after retooling')),
                ('last_state_height', models.PositiveIntegerField(help_text='Last height setting after retooling')),
            ],
            options={
                'verbose_name': 'Retooling Info',
                'verbose_name_plural': 'Retooling Info',
            },
        ),
        migrations.CreateModel(
            name='UnitPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('concrete_class', models.CharField(blank=True, max_length=10, null=True, verbose_name='Класс бетона')),
                ('price', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Цена')),
                ('unit', models.PositiveSmallIntegerField(choices=[(1, 'Плита'), (2, 'Проволока'), (3, 'Переналадка')], default=1, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Цена за единицу',
                'verbose_name_plural': 'Цены за единицу',
            },
        ),
        migrations.CreateModel(
            name='AvailableTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField()),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Избранная')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculation.contractor', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Available Track',
                'verbose_name_plural': 'Available Tracks',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DailyRetoolingChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_width', models.PositiveIntegerField(help_text='Original width setting')),
                ('from_height', models.PositiveIntegerField(help_text='Original height setting')),
                ('to_width', models.PositiveIntegerField(help_text='New width setting')),
                ('to_height', models.PositiveIntegerField(help_text='New height setting')),
                ('daily_retooling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='calculation.dailyretooling')),
            ],
            options={
                'verbose_name': 'Retooling Change',
                'verbose_name_plural': 'Retooling Changes',
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=255)),
                ('error_message', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('traceback', models.TextField()),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог ошибок',
                'verbose_name_plural': 'Логи ошибок',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_description', models.TextField()),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('error_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports', to='calculation.errorlog')),
            ],
            options={
                'verbose_name': 'Отчет об ошибке',
                'verbose_name_plural': 'Отчеты об ошибках',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='calculation.product', verbose_name='Изделие')),
                ('count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество, шт')),
            ],
            options={
                'verbose_name': 'Остаток',
                'verbose_name_plural': 'Остатки',
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'length', 'width', 'height', 'concrete_class', 'wire_top', 'wire_bottom'), name='unique_product'),
        ),
        migrations.CreateModel(
            name='LeftReadyPlate',
            fields=[
                ('plate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calculation.plate')),
            ],
            options={
                'verbose_name': 'Left Ready Plate',
                'verbose_name_plural': 'Left Ready Plates',
            },
            bases=('calculation.plate',),
        ),
        migrations.CreateModel(
            name='ProductionDayPlate',
            fields=[
                ('plate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calculation.plate')),
            ],
            options={
                'verbose_name': 'Production Day Plate',
                'verbose_name_plural': 'Production Day Plates',
            },
            bases=('calculation.plate',),
        ),
        migrations.CreateModel(
            name='UnplacedPlate',
            fields=[
                ('plate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calculation.plate')),
            ],
            options={
                'verbose_name': 'Unplaced Plate',
                'verbose_name_plural': 'Unplaced Plates',
            },
            bases=('calculation.plate',),
        ),
        migrations.CreateModel(
            name='UsedReadyPlate',
            fields=[
                ('plate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calculation.plate')),
            ],
            options={
                'verbose_name': 'Used Ready Plate',
                'verbose_name_plural': 'Used Ready Plates',
            },
            bases=('calculation.plate',),
        ),
        migrations.AddField(
            model_name='order',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calculation.contractor', verbose_name='Контрагент'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculation.product', verbose_name='Изделие'),
        ),
        migrations.AddConstraint(
            model_name='parameters',
            constraint=models.CheckConstraint(condition=models.Q(('tracks_count__gte', models.F('default_available_tracks'))), name='check_tracks_count', violation_error_message='Количество дорожек должно быть больше количества дорожек по умолчанию'),
        ),
        migrations.AddField(
            model_name='retoolinginfo',
            name='daily_retoolings',
            field=models.ManyToManyField(to='calculation.dailyretooling'),
        ),
        migrations.AddField(
            model_name='productiondayplate',
            name='production_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plates', to='calculation.productionday'),
        ),
    ]
