# Generated by Django 5.2 on 2025-05-12 12:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DailyRetooling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Daily Retooling',
                'verbose_name_plural': 'Daily Retoolings',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('length', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Длина, мм')),
                ('width', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ширина, мм')),
                ('height', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Высота, мм')),
                ('concrete_class', models.CharField(max_length=10, verbose_name='Класс бетона')),
                ('wire_bottom', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Проволока верх, шт')),
                ('wire_top', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Проволока низ, шт')),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
            },
        ),
        migrations.CreateModel(
            name='LeftReadyPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField()),
                ('length', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('order', models.CharField(blank=True, max_length=255, null=True)),
                ('concrete_class', models.CharField(max_length=10)),
                ('wire_bottom', models.PositiveIntegerField()),
                ('wire_top', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Left Ready Plate',
                'verbose_name_plural': 'Left Ready Plates',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, verbose_name='Номер заказа')),
                ('count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество, шт')),
                ('deadline', models.DateField(verbose_name='Дедавйн по заказу')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_length', models.PositiveIntegerField(verbose_name='Длина дорожки')),
                ('retooler_last_width', models.IntegerField(default=0, verbose_name='Последняя ширина переналадчика')),
                ('retooler_last_height', models.IntegerField(default=0, verbose_name='Последняя высота переналадчика')),
            ],
            options={
                'verbose_name': 'Parameters',
                'verbose_name_plural': 'Parameters',
            },
        ),
        migrations.CreateModel(
            name='ProductionDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('height', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('useful_len', models.PositiveIntegerField()),
                ('free_len', models.PositiveIntegerField()),
                ('concrete_class', models.CharField(max_length=10)),
                ('wire_bottom', models.PositiveIntegerField()),
                ('wire_top', models.PositiveIntegerField()),
                ('total_cost', models.FloatField()),
                ('free_cost', models.FloatField()),
                ('full_cost', models.FloatField()),
            ],
            options={
                'verbose_name': 'Production Day',
                'verbose_name_plural': 'Production Days',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ProductionDayPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField()),
                ('length', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('order', models.CharField(blank=True, max_length=255, null=True)),
                ('concrete_class', models.CharField(max_length=10)),
                ('wire_bottom', models.PositiveIntegerField()),
                ('wire_top', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Production Day Plate',
                'verbose_name_plural': 'Production Day Plates',
            },
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Production Plan',
                'verbose_name_plural': 'Production Plans',
            },
        ),
        migrations.CreateModel(
            name='RetoolingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('last_state_width', models.PositiveIntegerField()),
                ('last_state_height', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Retooling Info',
                'verbose_name_plural': 'Retooling Infos',
            },
        ),
        migrations.CreateModel(
            name='UnitPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('concrete_class', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('unit', models.PositiveSmallIntegerField(choices=[(1, 'Плита'), (2, 'Проволока'), (3, 'Переналадка')], default=1, verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='UnplacedPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField()),
                ('length', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('order', models.CharField(blank=True, max_length=255, null=True)),
                ('concrete_class', models.CharField(max_length=10)),
                ('wire_bottom', models.PositiveIntegerField()),
                ('wire_top', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Unplaced Plate',
                'verbose_name_plural': 'Unplaced Plates',
            },
        ),
        migrations.CreateModel(
            name='UsedReadyPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField()),
                ('length', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('order', models.CharField(blank=True, max_length=255, null=True)),
                ('concrete_class', models.CharField(max_length=10)),
                ('wire_bottom', models.PositiveIntegerField()),
                ('wire_top', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Used Ready Plate',
                'verbose_name_plural': 'Used Ready Plates',
            },
        ),
        migrations.CreateModel(
            name='DailyRetoolingChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_width', models.PositiveIntegerField()),
                ('from_height', models.PositiveIntegerField()),
                ('to_width', models.PositiveIntegerField()),
                ('to_height', models.PositiveIntegerField()),
                ('daily_retooling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='calculation.dailyretooling')),
            ],
            options={
                'verbose_name': 'Daily Retooling Changes',
                'verbose_name_plural': 'Daily Retoolings Changes',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='calculation.product', verbose_name='Изделие')),
                ('count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество, шт')),
            ],
            options={
                'verbose_name': 'Остаток',
                'verbose_name_plural': 'Остатки',
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'length', 'width', 'height', 'concrete_class', 'wire_top', 'wire_bottom'), name='unique_product'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculation.product', verbose_name='Изделие'),
        ),
        migrations.AddField(
            model_name='productiondayplate',
            name='production_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plates', to='calculation.productionday'),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='left_ready_plates',
            field=models.ManyToManyField(to='calculation.leftreadyplate'),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='plan',
            field=models.ManyToManyField(to='calculation.productionday'),
        ),
        migrations.AddField(
            model_name='retoolinginfo',
            name='daily_retoolings',
            field=models.ManyToManyField(to='calculation.dailyretooling'),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='retooling_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calculation.retoolinginfo'),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='unplaced_plates',
            field=models.ManyToManyField(to='calculation.unplacedplate'),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='used_ready_plates',
            field=models.ManyToManyField(to='calculation.usedreadyplate'),
        ),
    ]
