# Generated by Django 5.2 on 2025-05-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='default_available_tracks',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
