# Generated by Django 5.2 on 2025-05-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0002_parameters_default_available_tracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='last_used_mode',
            field=models.PositiveIntegerField(choices=[(0, 'Минимальная стоимость'), (1, 'Максимальное заполнение'), (2, 'Минимальное смешивание'), (3, 'Минимальные переналадки')], default=0),
        ),
    ]
