# Generated by Django 5.2 on 2025-05-26 05:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0003_parameters_last_used_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateField(verbose_name='Дедлайн по заказу'),
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=255)),
                ('error_message', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('traceback', models.TextField()),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог ошибок',
                'verbose_name_plural': 'Логи ошибок',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_description', models.TextField()),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('error_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports', to='calculation.errorlog')),
            ],
            options={
                'verbose_name': 'Отчет об ошибке',
                'verbose_name_plural': 'Отчеты об ошибках',
                'ordering': ['-timestamp'],
            },
        ),
    ]
