# Generated by Django 5.2 on 2025-05-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0004_alter_order_deadline_errorlog_errorreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameters',
            options={'verbose_name': 'Параметры', 'verbose_name_plural': 'Параметры'},
        ),
        migrations.AddField(
            model_name='parameters',
            name='sign_1c',
            field=models.CharField(default=123456788, max_length=255, verbose_name='Пароль 1с'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameters',
            name='url_1c',
            field=models.CharField(default='http://82.142.152.43/UPP/hs/slabs/all', max_length=255, verbose_name='URL 1c'),
            preserve_default=False,
        ),
    ]
