# Generated by Django 5.2 on 2025-05-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0005_alter_parameters_options_parameters_sign_1c_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitprice',
            options={'verbose_name': 'Цена за единицу', 'verbose_name_plural': 'Цены за единицу'},
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateField(null=True, verbose_name='Дедлайн по заказу'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='default_available_tracks',
            field=models.PositiveIntegerField(default=4, verbose_name='Количество дорожек по умолчанию'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='last_used_mode',
            field=models.PositiveIntegerField(choices=[(0, 'Минимальная стоимость'), (1, 'Максимальное заполнение'), (2, 'Минимальное смешивание'), (3, 'Минимальные переналадки')], default=0, verbose_name='Последний режим расчета'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='sign_1c',
            field=models.CharField(default='123456788', max_length=255, verbose_name='Пароль 1с'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='url_1c',
            field=models.CharField(default='', max_length=255, verbose_name='URL 1c'),
        ),
        migrations.AlterField(
            model_name='unitprice',
            name='concrete_class',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Класс бетона'),
        ),
        migrations.AlterField(
            model_name='unitprice',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
    ]
