# Generated by Django 5.2 on 2025-05-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0007_alter_order_options_alter_dailyretooling_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyretooling',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='productionday',
            name='free_cost',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='productionday',
            name='full_cost',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='productionday',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='retoolinginfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='unitprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Цена'),
        ),
    ]
