# Generated by Django 5.2 on 2025-06-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0008_alter_dailyretooling_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='friday_weekend',
            field=models.BooleanField(default=False, verbose_name='Пятница выходной'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='monday_weekend',
            field=models.BooleanField(default=False, verbose_name='Понедельник выходной'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='saturday_weekend',
            field=models.BooleanField(default=True, verbose_name='Суббота выходной'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='sunday_weekend',
            field=models.BooleanField(default=True, verbose_name='Воскресенье выходной'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='thursday_weekend',
            field=models.BooleanField(default=False, verbose_name='Четверг выходной'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='tuesday_weekend',
            field=models.BooleanField(default=False, verbose_name='Вторник выходной'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='wednesday_weekend',
            field=models.BooleanField(default=False, verbose_name='Среда выходной'),
        ),
    ]
