# Generated by Django 5.2 on 2025-06-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0009_parameters_friday_weekend_parameters_monday_weekend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='last_used_mode',
        ),
    ]
