# Generated by Django 5.2 on 2025-06-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0010_remove_parameters_last_used_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='production_lag',
            field=models.PositiveIntegerField(default=3, verbose_name='Производственный лаг (в днях)'),
        ),
    ]