# Generated by Django 5.2 on 2025-06-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0011_parameters_production_lag'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='tracks_count',
            field=models.PositiveIntegerField(default=7, verbose_name='Количество дорожек'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='friday_weekend',
            field=models.BooleanField(default=False, verbose_name='Пятница'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='monday_weekend',
            field=models.BooleanField(default=False, verbose_name='Понедельник'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='saturday_weekend',
            field=models.BooleanField(default=True, verbose_name='Суббота'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='sunday_weekend',
            field=models.BooleanField(default=True, verbose_name='Воскресенье'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='thursday_weekend',
            field=models.BooleanField(default=False, verbose_name='Четверг'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='tuesday_weekend',
            field=models.BooleanField(default=False, verbose_name='Вторник'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='wednesday_weekend',
            field=models.BooleanField(default=False, verbose_name='Среда'),
        ),
    ]
