# Generated by Django 5.2 on 2025-06-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0012_parameters_tracks_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='retooler_last_height',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='retooler_last_width',
        ),
    ]
