# Generated by Django 5.2 on 2025-06-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0013_remove_parameters_retooler_last_height_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='parameters',
            constraint=models.CheckConstraint(condition=models.Q(('tracks_count__gte', models.F('default_available_tracks'))), name='check_tracks_count', violation_error_message='Количество дорожек должно быть больше количества дорожек по умолчанию'),
        ),
    ]
