# Generated by Django 5.2 on 2025-06-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0014_parameters_check_tracks_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='tail_length',
            field=models.PositiveIntegerField(default=2000, help_text='Критическая длина хвоста в мм., при превышении которой хвост будет перенесен в конец', verbose_name='Длина хвоста'),
        ),
    ]
