# Generated by Django 5.2 on 2025-06-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0015_parameters_tail_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='force_tail',
            field=models.BooleanField(default=False, verbose_name='Переносить хвост в любом случае'),
        ),
    ]
