# Generated by Django 5.2 on 2025-06-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0016_parameters_force_tail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='force_tail',
            field=models.IntegerField(
                choices=[(0, 'Мягкий режим'), (1, 'Средний режим'), (2, 'Жесткий режим')],
                default=0,
                help_text='0 - мягкий режим, 1 - средний режим, 2 - жесткий режим',
                verbose_name='Режим переноса хвоста'
            ),
        ),
    ]