# Generated by Django 5.2 on 2025-09-27 16:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calculation Status',
                'verbose_name_plural': 'Calculation Statuses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HolidayDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Выходной день',
                'verbose_name_plural': 'Выходные дни',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=255)),
                ('error_message', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('traceback', models.TextField()),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог ошибок',
                'verbose_name_plural': 'Логи ошибок',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_description', models.TextField()),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('error_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports', to='calculation.errorlog')),
            ],
            options={
                'verbose_name': 'Отчет об ошибке',
                'verbose_name_plural': 'Отчеты об ошибках',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Export1c',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('track_position', models.PositiveSmallIntegerField()),
            ],
            options={
                'unique_together': {('date', 'track_position')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, verbose_name='Номер заказа')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculation.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='calculation.order')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_length', models.PositiveIntegerField(verbose_name='Длина дорожки')),
                ('default_available_tracks', models.PositiveIntegerField(default=4, verbose_name='Количество дорожек по умолчанию')),
                ('tracks_count', models.PositiveIntegerField(default=7, verbose_name='Количество дорожек')),
                ('production_lag', models.PositiveIntegerField(default=3, verbose_name='Производственный лаг (в днях)')),
                ('tail_length', models.PositiveIntegerField(default=2000, help_text='Критическая длина хвоста в мм., при превышении которой хвост будет перенесен в конец', verbose_name='Длина хвоста')),
                ('force_tail', models.IntegerField(choices=[(0, 'Мягкий режим'), (1, 'Средний режим'), (2, 'Жесткий режим')], default=0, help_text='0 - мягкий режим, 1 - средний режим, 2 - жесткий режим', verbose_name='Режим переноса хвоста')),
                ('url_1c', models.CharField(default='', max_length=255, verbose_name='URL 1c')),
                ('url_1c_export', models.CharField(default='', max_length=255, verbose_name='URL 1c Export')),
                ('sign_1c', models.CharField(default='123456788', max_length=255, verbose_name='Пароль 1с')),
                ('monday_weekend', models.BooleanField(default=False, verbose_name='Понедельник')),
                ('tuesday_weekend', models.BooleanField(default=False, verbose_name='Вторник')),
                ('wednesday_weekend', models.BooleanField(default=False, verbose_name='Среда')),
                ('thursday_weekend', models.BooleanField(default=False, verbose_name='Четверг')),
                ('friday_weekend', models.BooleanField(default=False, verbose_name='Пятница')),
                ('saturday_weekend', models.BooleanField(default=True, verbose_name='Суббота')),
                ('sunday_weekend', models.BooleanField(default=True, verbose_name='Воскресенье')),
            ],
            options={
                'verbose_name': 'Параметры',
                'verbose_name_plural': 'Параметры',
                'constraints': [models.CheckConstraint(condition=models.Q(('tracks_count__gte', models.F('default_available_tracks'))), name='check_tracks_count', violation_error_message='Количество дорожек должно быть больше количества дорожек по умолчанию')],
            },
        ),
        migrations.CreateModel(
            name='ReadyPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('concrete_class', models.CharField(max_length=50)),
                ('wire_bottom', models.CharField(max_length=50)),
                ('wire_top', models.CharField(max_length=50)),
                ('height', models.FloatField()),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('used_in_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ready_plates', to='calculation.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('day', models.DateField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculation.customer')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('concrete_class', models.CharField(max_length=50)),
                ('wire_bottom', models.CharField(max_length=50)),
                ('wire_top', models.CharField(max_length=50)),
                ('height', models.FloatField()),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('is_manual', models.BooleanField(default=False)),
                ('deadline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plates', to='calculation.deadline')),
                ('track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plates', to='calculation.track')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('concrete_class', models.CharField(blank=True, max_length=10, null=True, verbose_name='Класс бетона')),
                ('price', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Цена')),
                ('unit', models.PositiveSmallIntegerField(choices=[(1, 'Плита'), (2, 'Проволока'), (3, 'Переналадка')], default=1, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Цена за единицу',
                'verbose_name_plural': 'Цены за единицу',
                'constraints': [models.UniqueConstraint(condition=models.Q(('unit', 3)), fields=('unit',), name='unique_retooling_unit'), models.UniqueConstraint(condition=models.Q(('unit', 2)), fields=('unit',), name='unique_wire_unit')],
            },
        ),
    ]
