# Generated by Django 5.2 on 2025-06-26 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('calculation', '0001_initial'),
    ]

    operations = [
    ]