# Generated by Django 5.2 on 2025-07-28 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0002_auto_20250728_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plate',
            name='count',
        ),
        migrations.RemoveField(
            model_name='readyplate',
            name='count',
        ),
    ]
