# Generated by Django 5.2 on 2025-08-08 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0003_remove_plate_count_remove_readyplate_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deadline',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['day']},
        ),
        migrations.AlterField(
            model_name='deadline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='calculation.order'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='deadline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plates', to='calculation.deadline'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plates', to='calculation.track'),
        ),
        migrations.AddConstraint(
            model_name='unitprice',
            constraint=models.UniqueConstraint(condition=models.Q(('unit', 3)), fields=('unit',), name='unique_retooling_unit'),
        ),
        migrations.AddConstraint(
            model_name='unitprice',
            constraint=models.UniqueConstraint(condition=models.Q(('unit', 2)), fields=('unit',), name='unique_wire_unit'),
        ),
    ]
