# Generated by Django 5.2 on 2025-08-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0004_alter_deadline_options_alter_track_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
