# Generated by Django 5.2 on 2025-08-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0005_track_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AddField(
            model_name='readyplate',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
    ]
