# Generated by Django 5.2 on 2025-08-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0006_plate_is_deleted_readyplate_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='readyplate',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
