# Generated by Django 5.2 on 2025-08-25 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0007_readyplate_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readyplate',
            name='is_used',
        ),
        migrations.AddField(
            model_name='readyplate',
            name='used_in_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ready_plates', to='calculation.order'),
        ),
    ]
