# Generated by Django 5.2 on 2025-08-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0009_holidaydate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export1c',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
