# Generated by Django 5.2 on 2025-06-26 10:44
from django.db import models
from django.core import serializers
from django.db import migrations

parameters_dump = """[
{
  "model": "calculation.parameters",
  "pk": 1,
  "fields": {
    "road_length": 85000,
    "default_available_tracks": 5,
    "tracks_count": 7,
    "production_lag": 3,
    "tail_length": 1000,
    "force_tail": 2,
    "url_1c": "http://82.142.152.43/UPP/hs/slabs/all",
    "url_1c_export": "http://82.142.152.43/UPP/hs/slabs/opzs",
    "sign_1c": "123456788",
    "monday_weekend": false,
    "tuesday_weekend": false,
    "wednesday_weekend": false,
    "thursday_weekend": false,
    "friday_weekend": false,
    "saturday_weekend": true,
    "sunday_weekend": true
  }
}
]"""

unitprice_dump = """[
{
  "model": "calculation.unitprice",
  "fields": {
    "name": "Бетон В25 М350",
    "concrete_class": "В25",
    "price": "5500.00",
    "unit": 1
  }
},
{
  "model": "calculation.unitprice",
  "fields": {
    "name": "Бетон В30 М400",
    "concrete_class": "В30",
    "price": "6000.00",
    "unit": 1
  }
},
{
  "model": "calculation.unitprice",
  "fields": {
    "name": "Бетон В35 М450",
    "concrete_class": "В35",
    "price": "6500.00",
    "unit": 1
  }
},
{
  "model": "calculation.unitprice",
  "fields": {
    "name": "Бетон В40 М500",
    "concrete_class": "В40",
    "price": "7000.00",
    "unit": 1
  }
},
{
  "model": "calculation.unitprice",
  "fields": {
    "name": "Проволока",
    "concrete_class": null,
    "price": "15.00",
    "unit": 2
  }
},
{
  "model": "calculation.unitprice",
  "fields": {
    "name": "Переналадка",
    "concrete_class": null,
    "price": "15000.00",
    "unit": 3
  }
}
]"""


def load_parameters(apps, schema_editor):
    for obj in serializers.deserialize("json", parameters_dump):
        obj.save()


def delete_parameters(apps, schema_editor):
    Parameters = apps.get_model("calculation", "Parameters")
    Parameters.objects.filter(pk=1).delete()


def load_unitprices(apps, schema_editor):
    for obj in serializers.deserialize("json", unitprice_dump):
        obj.save()


def delete_unitprices(apps, schema_editor):
    UnitPrice = apps.get_model("calculation", "UnitPrice")
    UnitPrice.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0010_export1c'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='url_1c_export',
            field=models.CharField(default='', max_length=255, verbose_name='URL 1c'),
        ),
        migrations.RunPython(
            code=load_parameters,
            reverse_code=delete_parameters
        ),
        migrations.RunPython(
            code=load_unitprices,
            reverse_code=delete_unitprices
        )
    ]
