# Generated by Django 5.2 on 2025-09-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0011_parameters_url_1c_export'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calculation Status',
                'verbose_name_plural': 'Calculation Statuses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='parameters',
            name='url_1c_export',
            field=models.CharField(default='', max_length=255, verbose_name='URL 1c Export'),
        ),
    ]
