# Generated by Django 5.2 on 2025-09-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0012_calculationstatus_alter_parameters_url_1c_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
