# Generated by Django 5.2 on 2025-09-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0013_plate_is_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='is_manual',
        ),
    ]
